# fly.toml app configuration file generated for backend-botwhatsapp on 2025-08-04T17:11:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-botwhatsapp'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
